### ISSUE TITLE
Declare dependency on python-distribute

### ISSUE THREAD

**Issue by smapjb** [enversion/enversion#6] opened 2013-09-24 08:42 UTC
It is possible to install (without forcing) the bdist_rpm.. but on running you get

Traceback (most recent call last):
  File "/usr/bin/evnadmin", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources

So there needs to be a declaration of dependency in the rpm on setuptools. On my system this is python26-distribute

Not sure why it needs this could be a bug.

**Comment by tpn** [comment] 2015-02-03 13:03
@smapjb don't suppose you have a patch for this?  Looking to close if the issue is obsolete.  If it's still happening then it'd be good to fix it properly.

**Comment by tpn** [comment] 2015-02-16 16:32
Closing for now, I'm pretty sure this is obsolete.

**Closed by tpn** 2015-02-16 16:32 UTC
